name: deploy to production
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: pull
      run: |
        cd /home/BOT-1.0/.github/workflows
        git stash
        git pull origin master
        npm install
